### PR TITLE
Fixes #411 Export branch fails

### LINKED ISSUE #411: Export branch fails
Project: https://drive.google.com/file/d/0B6icounl9q69VDVLNTVVWDhfcmc/view?usp=sharing

Server:
```
Wrong node Error: isobject
    at __test (/home/hakan/github/webgme/webgme/src/common/core/corerel.js:34:19)
    at Object.isValidNode (/home/hakan/github/webgme/webgme/src/common/core/corerel.js:53:17)
    at isValidNode (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:38:40)
    at Object.core.getBase (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:60:20)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:87)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:64)
    at Object.core.loadChildren (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:207:31)
    at Object.core.loadSubTree (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:47:21)
    at loadSubTrees (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:28:37)
    at /home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:45:24
Wrong node Error: core
    at __test (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:32:23)
    at isValidNode (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:38:17)
    at Object.core.getBase (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:60:20)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:87)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:64)
    at Object.core.loadChildren (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:207:31)
    at Object.core.loadSubTree (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:47:21)
    at loadSubTrees (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:28:37)
    at /home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:45:24
    at tasync_trace_start [as onResolved] (/home/hakan/github/webgme/webgme/src/common/core/tasync.js:366:35)
Throwing Error: ASSERT failed
    at assert (/home/hakan/github/webgme/webgme/src/common/util/assert.js:14:25)
    at Object.core.getBase (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:60:13)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:87)
    at Object.core.getChildrenRelids (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:195:64)
    at Object.core.loadChildren (/home/hakan/github/webgme/webgme/src/common/core/coretype.js:207:31)
    at Object.core.loadSubTree (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:47:21)
    at loadSubTrees (/home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:28:37)
    at /home/hakan/github/webgme/webgme/src/common/core/coretreeloader.js:45:24
    at tasync_trace_start [as onResolved] (/home/hakan/github/webgme/webgme/src/common/core/tasync.js:366:35)
    at Future.resolve (/home/hakan/github/webgme/webgme/src/common/core/tasync.js:53:26)
....
```
Full server side error: https://drive.google.com/file/d/0B6icounl9q69Vi13QVVLX1VRMGM/view?usp=sharing

Client:
url:
```
http://localhost:8888/worker/simpleResult/9954a2b1-90b0-9d9a-ce51-a4930419c263/a27_np_master
```
page:
```
Internal Server Error
```
console:
```
GET http://localhost:8888/favicon.ico 404 (Not Found)
```

### PR DESCRIPTION
**Pull request by kecso**
The export format changes so that it filters out 'dataless' nodes that only have their GUIDs as information.
The format and the functions remained backward compatible thought it is advisable to recreate the snaphots of the projects.

### CODE REVIEW

File: src/common/core/users/serialization.js [hunk 1]
```diff
@@ -30,17 +30,440 @@ define(['common/util/assert', 'blob/BlobConfig'], function (ASSERT, BlobConfig)
     }
```
Comment (pmeijer) [inline src/common/core/users/serialization.js]: While you're working on this file, can't you make it stateless?
I can see use-cases where exports are invoked before one has finished.

Comment (kecso) [inline src/common/core/users/serialization.js]: the added functionality is stateless now, but I can refactor the old as well
