### PR TITLE
Fixes #410 instance loading bug

### LINKED ISSUE #410: Instance of an object doesn't load properly
(Grand\*)child of an instance of an object loads as **undefined**. The exported project with mongoexport can be downloaded at https://drive.google.com/file/d/0B6icounl9q69VDVLNTVVWDhfcmc/view?usp=sharing.

WebGME shows the child of P10 as undefined:
```
ROOT > apps > Blink > BlinkAppC > LedsC > PlatformLedsC > HplMsp430GeneralIOC > P10 > undefined
```

The original object:
```
ROOT > tos > platforms > exp430 > hardware > leds > PlatformLedsC > HplMsp430GeneralIOC > P10 > IO
```

### PR DESCRIPTION
**Pull request by kecso**

### CODE REVIEW

File: src/common/core/coretype.js [hunk 1]
```diff
@@ -39,7 +39,11 @@ define(['common/util/assert', 'common/core/core', 'common/core/tasync'], functio
                 __test('base', typeof node.base === 'object');
                 return true;
             } catch (error) {
-                console.log('Wrong node', error.stack);
+                logger.error('invalid node', {
```
Comment (lattmann) [inline src/common/core/coretype.js]: use `logger.error(message, {metadata: { stack: error.stack, node: node}})`
