### PR TITLE
Moved bug replay downloading to CR3. Fixes #413.

### LINKED ISSUE #413: Autorouter Replay Download not available with Web Worker
Moving the autorouter to a web worker made it unable to download replay events for debugging.

### PR DESCRIPTION
**Pull request by brollb**
Moved the downloading functionality to the ConnectionRouteManager rather than the AutoRouter.ActionApplier. 

Unfortunately, I am unsure how to check if something got downloaded so I haven't created any automated tests.

### CODE REVIEW

**Comment by lattmann** [comment]
Thanks: @brollb

File: src/client/js/Widgets/DiagramDesigner/ConnectionRouteManager3.js [hunk 1]
```diff
@@ -576,5 +583,31 @@ define([
         return newBox;
     };
 
+    ConnectionRouteManager3.prototype.download = function (filename, data) {
+        if (!this.readyToDownload) {
```
Comment (pmeijer) [inline src/client/js/Widgets/DiagramDesigner/ConnectionRouteManager3.js]: Will this.readyToDownload ever be true? I can't see where it is ever set to true (at least not in the diff).

**Comment by lattmann** [comment]
It is set here: https://github.com/webgme/webgme/blob/issue/413_autorouter_worker_replay/src/client/js/Widgets/DiagramDesigner/ConnectionRouteManager3.js#L294
