### PR TITLE
Fixes #1489 Non-meta nodes in aspects throws exception in getValidChildrenMetaNodes

### LINKED ISSUE #1489: Non-meta nodes in aspects throws exception in getValidChildrenMetaNodes
It should be noted that a meta like that is reported as inconsistent.

The same issue most likely holds for containment and sets members too.

```
Uncaught TypeError: Cannot read property 'relid' of undefined
    at MetaCore.CoreTree.getPath (:8888/common/core/coretree.js:391)
    at sameNode (:8888/common/core/metacore.js:33)
    at MetaCacheCore.MetaCore.isTypeOf (:8888/common/core/metacore.js:138)
    at isTypeOf (:8888/common/core/mixincore.js:313)
    at MixinCore.isTypeOf (:8888/common/core/mixincore.js:390)
    at Object.MetaQueryCore.getValidChildrenMetaNodes (:8888/common/core/metaquerycore.js:148)
    at CoreQ.Core.getValidChildrenMetaNodes (:8888/common/core/core.js:3207)
    at GMENode.getValidChildrenTypesDetailed (:8888/js/client/gmeNodeGetter.js:361)
    at PartBrowserControl._getPartDescriptorCollection (:8888/panel/PartBrowser/PartBrowserPanelControl.js:302)
    at :8888/panel/PartBrowser/PartBrowserPanelControl.js:81
```

### PR DESCRIPTION
**Pull request by kecso**
As out-of-meta nodes can be part of meta rules, these specific inquiry functions should be prepared for that scenario.
The function results remains the same, but it will work only with the paths of the rule related nodes instead of trying to get them from all the meta nodes.

### CODE REVIEW

File: src/common/core/metaquerycore.js [hunk 1]
```diff
@@ -98,21 +98,10 @@ define([
...
-                    } else {
-                        delete rules[keys[i]];
-                    }
-                }
-
                 keys = Object.keys(rules);
                 for (i = 0; i < children.length; i += 1) {
                     for (j = 0; j < keys.length; j += 1) {
-                        if (innerCore.isTypeOf(children[i], metaNodes[keys[j]])) {
+                        if (innerCore.isTypeOfPath(children[i], keys[j])) {
```
Comment (pmeijer) [inline src/common/core/metaquerycore.js]: Can't this method be exposed on the core? Or alternatively `isTypeOf` could accept both a node and path as the second argument. What definitely should be done is to merge the implementation of these two.

File: src/client/js/client/gmeNodeSetter.js [hunk 2]
```diff
@@ -999,11 +999,10 @@ define([], function () {
         // TODO: These should be removed at next version bump.
 
         function isTypeOf(path, typePath) {
-            var node = _getNode(path),
-                typeNode = _getNode(typePath);
+            var node = _getNode(path);
```
Comment (pmeijer) [inline src/client/js/client/gmeNodeSetter.js]: This method will throw an undefined error
