### PR TITLE
Fixes #515

### LINKED ISSUE #515: Exporting project / library under Safari fails

### PR DESCRIPTION
**Pull request by kecso**
Changing parameters of download links (target='_self') so it work until Safari as well

### CODE REVIEW

File: src/client/js/Utils/SaveToDisk.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
+/*globals define*/
+/*jshint node: true, browser: true, bitwise: false*/
+
+/**
+ * @author kecso / https://github.com/kecso
+ */
+define(function () {
+    'use strict';
+
+    var saveToDisk = function (fileURL, fileName) {
```
Comment (pmeijer) [inline src/client/js/Utils/SaveToDisk.js]: Was this code snippet coming from some external source, e.g. stack overflow? If so it's good to add a link.

File: src/server/standalone.js [hunk 2]
```diff
@@ -852,24 +852,20 @@ function StandAloneServer(gmeConfig) {
                 logger.error('worker/simpleResult err', err);
                 res.sendStatus(500);
             } else {
-                res.header('Content-Disposition', 'attachment;filename=\'' + filename + '\'');
+                res.header('Content-Disposition', 'attachment;filename=' + filename);
```
Comment (ksmyth) [inline src/server/standalone.js]: This will be wrong if filename contains `%` or non-ASCII. Use https://www.npmjs.com/package/content-disposition

Comment (lattmann) [inline src/server/standalone.js]: +1
