### PR TITLE
Fixes #856 Project import fails with exception

### LINKED ISSUE #856: Project import fails with exception.
```
Throwing Error: ASSERT failed
    at assert (C:\GIT\webgme\src\common\util\assert.js:14:25)
    at CoreQ.getBase (C:\GIT\webgme\src\common\core\coretype.js:794:13)
    at updateInheritance (C:\GIT\webgme\src\common\core\users\serialization.js:994:29)
    at C:\GIT\webgme\src\common\core\users\serialization.js:1392:21
    at loadImportBases (C:\GIT\webgme\src\common\core\users\serialization.js:887:17)
    at C:\GIT\webgme\src\common\core\users\serialization.js:1336:17
    at C:\GIT\webgme\src\common\core\users\serialization.js:823:13
    at C:\GIT\webgme\node_modules\q\q.js:2027:17
    at runSingle (C:\GIT\webgme\node_modules\q\q.js:137:13)
    at flush (C:\GIT\webgme\node_modules\q\q.js:125:13)

2016-02-25T16:58:18.194Z - error: uncaughtException: ASSERT failed
{ date: 'Thu Feb 25 2016 10:58:18 GMT-0600 (Central Standard Time)',
  process:
   { pid: 10160,
     uid: null,
     gid: null,
     cwd: 'C:\\GIT\\webgme',
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     version: 'v0.12.7',
     argv:
      [ 'C:\\Program Files\\nodejs\\node.exe',
        'C:\\GIT\\webgme\\src\\server\\worker\\simpleworker.js' ],
     memoryUsage: { rss: 102354944, heapTotal: 88684032, heapUsed: 57776952 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 1131647.3574798 },
  trace:
   [ { column: 25,
       file: 'C:\\GIT\\webgme\\src\\common\\util\\assert.js',
       function: 'assert',
       line: 14,
       method: null,
       native: false },
     { column: 13,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\coretype.js',
       function: 'CoreQ.getBase',
       line: 794,
       method: 'getBase',
       native: false },
     { column: 29,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js',
       function: 'updateInheritance',
       line: 994,
       method: null,
       native: false },
     { column: 21,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js',
       function: null,
       line: 1392,
       method: null,
       native: false },
     { column: 17,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js',
       function: 'loadImportBases',
       line: 887,
       method: null,
       native: false },
     { column: 17,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js',
       function: null,
       line: 1336,
       method: null,
       native: false },
     { column: 13,
       file: 'C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js',
       function: null,
       line: 823,
       method: null,
       native: false },
     { column: 17,
       file: 'C:\\GIT\\webgme\\node_modules\\q\\q.js',
       function: null,
       line: 2027,
       method: null,
       native: false },
     { column: 13,
       file: 'C:\\GIT\\webgme\\node_modules\\q\\q.js',
       function: 'runSingle',
       line: 137,
       method: null,
       native: false },
     { column: 13,
       file: 'C:\\GIT\\webgme\\node_modules\\q\\q.js',
       function: 'flush',
       line: 125,
       method: null,
       native: false } ],
  stack:
   [ 'Error: ASSERT failed',
     '    at assert (C:\\GIT\\webgme\\src\\common\\util\\assert.js:14:25)',
     '    at CoreQ.getBase (C:\\GIT\\webgme\\src\\common\\core\\coretype.js:794:13)',
     '    at updateInheritance (C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js:994:29)',
     '    at C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js:1392:21',
     '    at loadImportBases (C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js:887:17)',
     '    at C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js:1336:17',
     '    at C:\\GIT\\webgme\\src\\common\\core\\users\\serialization.js:823:13',
     '    at C:\\GIT\\webgme\\node_modules\\q\\q.js:2027:17',
     '    at runSingle (C:\\GIT\\webgme\\node_modules\\q\\q.js:137:13)',
     '    at flush (C:\\GIT\\webgme\\node_modules\\q\\q.js:125:13)' ] }
```

### PR DESCRIPTION
**Pull request by kecso**
- There is an issue of GUID collision (by multiple import of the same library/model), which results in a corrupted export that cannot be imported
- The correction fixes the issue at source, meaning it offers GUID reallocation on export (or simply leaves out the colliding nodes)
- The correction also introduces the _metadata into the export format, so it can be checked if an export is a full project or a library and we can reject the import based on this information.

### CODE REVIEW

**Comment by pmeijer** [comment]
This seems to be failing w.r.t. to client test.

**Comment by kecso** [comment]
tests should be fixed now

File: src/common/core/constants.js [hunk 1]
```diff
@@ -50,6 +50,9 @@ define([], function () {
             CONSTRAINT_COLLISION: 'constraint collision'
         },
 
+        EXPORT_TYPE_FULL_PROJECT: 'full',
```
Comment (pmeijer) [inline src/common/core/constants.js]: Isn't 'project' more suiting? Like 'library' and 'project', vs 'library' and 'full'?

Comment (kecso) [inline src/common/core/constants.js]: you are right. I will change it to simply EXPORT_TYPE_PROJECT: 'project'

File: src/server/worker/workerrequests.js [hunk 2]
```diff
@@ -95,6 +97,55 @@ function WorkerRequests(mainLogger, gmeConfig) {
...
+    }
+
+    function _checkGuidsNodeByNode(core, root) {
+        var taskQueue = [''],
+            working = false,
+            timerId,
+            deferred = Q.defer(),
+            guids = {};
+
+        timerId = setInterval(function () {
```
Comment (pmeijer) [inline src/server/worker/workerrequests.js]: Is this a well-known pattern for doing recursions?

File: src/client/js/client.js [hunk 3]
```diff
@@ -2015,6 +2017,68 @@ define([
...
+        this.checkImport = function (jsonImport, importType) {
+            if (!jsonImport) {
+                return 'Import should always be a valid JSON object!';
+            }
+
+            switch (importType) {
+                case CORE_CONSTANTS.EXPORT_TYPE_FULL_PROJECT:
+                    if (jsonImport._metadata && jsonImport._metdata.type) {
+                        if (jsonImport._metadata.type !== CORE_CONSTANTS.EXPORT_TYPE_FULL_PROJECT) {
+                            return 'Import is of type \'library\' and not of \'full project\'!';
```
Comment (pmeijer) [inline src/client/js/client.js]: Update the name here too, even better use the constants the error message.

Comment (pmeijer) [inline src/client/js/client.js]: Couldn't this be a method within serialization? The client is pretty packed as it is and this doesn't use the state as far as I can see.

**Comment by pmeijer** [comment]
I'm done with my comments, can't wait to get an import/export error :)

File: src/client/js/client.js (hunk 3 above)
Comment (kecso) [inline src/client/js/client.js]: right, I will move it there, but it needs a client 'proxy' anyhow...

File: src/server/worker/workerrequests.js (hunk 2 above)
Comment (kecso) [inline src/server/worker/workerrequests.js]: I am not sure how to respond to this question:
- I think it is nothing libraryish, but we used it multiple times as this is the only real replacement for recursion (which could be an issue if you have too deep hierarchy)

File: src/client/js/Controls/PropertyGrid/Widgets/AssetWidget.js [hunk 4]
```diff
@@ -228,6 +231,36 @@ define([
         return bytes.toFixed(1) + ' ' + units[u];
     };
 
+    AssetWidget.prototype.getTargetAsJson = function (callback) {
```
Comment (pmeijer) [inline src/client/js/Controls/PropertyGrid/Widgets/AssetWidget.js]: For future uses - it would be nice to have a getTargetAsText too..

File: src/client/js/Dialogs/ExportErrors/ExportErrorsDialog.js [hunk 5]
```diff
@@ -0,0 +1,77 @@
+/*globals define, $*/
+/*jshint browser: true*/
+
+/**
+ * Dialog for confirmation of project deletion.
+ *
+ * @author pmeijer / https://github.com/pmeijer
```
Comment (pmeijer) [inline src/client/js/Dialogs/ExportErrors/ExportErrorsDialog.js]: I don't remember writing this dialog ;)

**Comment by pmeijer** [comment]
Tamas, I will merge this. But will also create a 1.6.0 issue to add tests. Esp. regarding the new worker-request.
