### PR TITLE
Fixes #785 URL query for node is not working for paths with non-numbers.

### LINKED ISSUE #785: URL query for node is not working for paths with non-numbers.

### PR DESCRIPTION
**Pull request by kecso**
Now a library is used for uri query string parsing.
The node parameter of the query is not transformed to lower case as it can have both upper and lower case characters now.

### CODE REVIEW

File: src/client/js/main.js [hunk 1]
```diff
@@ -78,6 +78,8 @@ require.config({
 
         moment: 'lib/moment/moment.min',
 
+        urlparse:'lib/purl/purl.min',
```
Comment (lattmann) [inline src/client/js/main.js]: Add space next time.

File: src/client/js/util.js [hunk 2]
```diff
@@ -105,12 +105,13 @@ define([], function () {
         },
 
         getURLParameterByName: function (name) {
-            var regex,
-                results;
-            name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
-            regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
-            results = regex.exec(location.search);
-            return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
+            var queryParams = URLPARSE(location,true).param();
```
Comment (lattmann) [inline src/client/js/util.js]: Style, space is missing between function parameters.
